# llm-d-monitoring/limitador-servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: limitador
  namespace: llm-d-monitoring           # ← Same namespace as Prometheus
  labels:
    release: prometheus
    app.kubernetes.io/name: limitador
    app.kubernetes.io/component: limitador
spec:
  # Still scrape the Service that lives in the kuadrant-system namespace
  namespaceSelector:
    matchNames:
      - kuadrant-system
  selector:
    matchLabels:
      app: limitador                    # matches Service’s only label
  endpoints:
    - port: http
      path: /metrics
      scheme: http
      interval: 30s
      scrapeTimeout: 10s
