# WIP - broken atm
apiVersion: batch/v1
kind: CronJob
metadata:
  name: llmd-external-cost-smoke
  namespace: llm-d-monitoring
spec:
  schedule: "*/2 * * * *"            # every 2minutes
  concurrencyPolicy: Replace         # replace any still-running job
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: llmd-external-cost
          restartPolicy: Never
          containers:
            - name: smoke
              image: curlimages/curl:8.8.0
              imagePullPolicy: IfNotPresent
              env:
                - name: PROM_URL
                  value: "http://prometheus-kube-prometheus-prometheus.llm-d-monitoring.svc.cluster.local:9090"
              command:
                - /bin/sh
                - -c
                - |
                  set -eu
                  echo "==> Querying Prometheus for llmd_request_cost_usd_24h_total"
                  curl -sG \
                    --data-urlencode "query=llmd_request_cost_usd_24h_total" \
                    "${PROM_URL}/api/v1/query"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: llmd-external-cost
  namespace: llm-d-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: llmd-external-cost
  namespace: opencost
rules:
  - apiGroups: ["opencost.io"]
    resources: ["externalcosts"]
    verbs: ["get","list","watch","create","update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: llmd-external-cost
  namespace: opencost
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: llmd-external-cost
subjects:
  - kind: ServiceAccount
    name: llmd-external-cost
    namespace: llm-d-monitoring
